spring.application.name=DoctorService

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/doctor_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/